version: '3'
services:
  client:
    image: strangesast/pool-temp-sensor_client
    build: client-simple
    ports:
      - 80:80
      - 443:443
  server:
    image: strangesast/pool-temp-sensor_server-go
    build: server-go
    environment:
      - MONGO_HOST=mongo
  mongo:
    image: "mongo"
