# Set this if the IDE is not in your $PATH or you want to use a specific version:
#ARDUINO_DIR = /opt/arduino-1.8.9

# Programmer type:
ISP_PROG = usbasp

ALTERNATE_CORE = ATTinyCore
BOARD_TAG = attinyx5
BOARD_SUB = 85
VARIANT = tinyX5
F_CPU = 8000000L

# Path to the Arduino Makefile
include ./Arduino-Makefile/Arduino.mk

# !!! Important. You have to use 'make ispload' when using an ISP.
