version: '3.7'
services:
  monitor:
    build:
      context: .
      dockerfile: docker/monitor/Dockerfile
    environment:
      - PG_HOST=postgres
      - PG_DB_NAME=temps
      - PG_USER=postgres
      - PG_PASSWORD=password
      - PORT=3000
    ports:
      - "3000:3000"
  server:
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    ports:
      - "8080:80"
    environment:
      NODE_CONFIG: '{"postgres":{"host": "postgres", "user": "postgres", "password": "password"}, "port": 80}'
  postgres:
    image: postgres
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=temps
volumes:
  db_data:
